In [4]:
import pandas as pd
import numpy as np

In [5]:
fertilizerPrediction=pd.read_csv("../data/datafertilizerprediction.csv")

In [6]:
frUnique=pd.unique(fertilizerPrediction["Fertilizer"].str.lower())
stUnique=pd.unique(fertilizerPrediction["Soil Type"].str.lower())
ctUnique=pd.unique(fertilizerPrediction["Crop Type"].str.lower())

print("Crop Recommendation Unique Crops: ",frUnique)
print("Crop Recommendation Unique Crops: ",stUnique)
print("Crop Recommendation Unique Crops: ",ctUnique)

Crop Recommendation Unique Crops:  ['urea' 'dap' '14-35-14' '28-28' '17-17-17' '20-20' '10-26-26']
Crop Recommendation Unique Crops:  ['sandy' 'loamy' 'black' 'red' 'clayey']
Crop Recommendation Unique Crops:  ['maize' 'sugarcane' 'cotton' 'tobacco' 'paddy' 'barley' 'wheat' 'millets'
 'oil seeds' 'pulses' 'ground nuts']


In [12]:
fertilizerPrediction['Fertilizer']=fertilizerPrediction['Fertilizer'].astype('category')
fertilizerPrediction['Soil Type']=fertilizerPrediction['Soil Type'].astype('category')
fertilizerPrediction['Crop Type']=fertilizerPrediction['Crop Type'].astype('category')

In [14]:
fertilizerPrediction['Fertilizer']=fertilizerPrediction['Fertilizer'].cat.codes
fertilizerPrediction['Soil Type']=fertilizerPrediction['Soil Type'].cat.codes
fertilizerPrediction['Crop Type']=fertilizerPrediction['Crop Type'].cat.codes

In [16]:
fer=pd.unique(fertilizerPrediction['Fertilizer'])
st=pd.unique(fertilizerPrediction['Soil Type'])
ct=pd.unique(fertilizerPrediction['Crop Type'])


print("Crop Recommendation Unique Crops: ",fer)
print("Crop Recommendation Unique Crops: ",st)
print("Crop Recommendation Unique Crops: ",ct)

Crop Recommendation Unique Crops:  [6 5 1 4 2 3 0]
Crop Recommendation Unique Crops:  [4 2 0 3 1]
Crop Recommendation Unique Crops:  [ 3  8  1  9  6  0 10  4  5  7  2]


In [18]:
print(frUnique)
print(fer)

print()
print()

print(stUnique)
print(st)

print()
print()

print(ctUnique)
print(ct)

['urea' 'dap' '14-35-14' '28-28' '17-17-17' '20-20' '10-26-26']
[6 5 1 4 2 3 0]


['sandy' 'loamy' 'black' 'red' 'clayey']
[4 2 0 3 1]


['maize' 'sugarcane' 'cotton' 'tobacco' 'paddy' 'barley' 'wheat' 'millets'
 'oil seeds' 'pulses' 'ground nuts']
[ 3  8  1  9  6  0 10  4  5  7  2]
